### ISSUE TITLE
Проблема базы данных

### ISSUE THREAD

**Issue by 1inkin** [PavelSyomin/proofreader#2]
В панели управления Joomla 4.2.5 проверка базы данных показывает предупреждение о наличие проблем, связанных с компонентом. Автоматическое исправление результатов не дает.

**Comment by PavelSyomin** [comment]
Попробуйте обновиться до версии 2.1.3 (лучше всего через автоматическое обновление — заодно проверю, что оно работает).

**Comment by 1inkin** [comment]
Автоматически обновился до версии 2.1.4. Проблема с базой данных устранилась. Спасибо
