### ISSUE TITLE
Overlay

### ISSUE THREAD

**Issue by 1inkin** [PavelSyomin/proofreader#3]
Класс proofreader_overlay, который закрывает собой всю площадь страницы, по умолчанию использует в css `background` картинку для размытия фона. Но, если заменить этот способ на `opacity: 0.5`, то вместе с фоном прозрачным становится и окно отправки сообщения об ошибке. Установить для окна `opacity: 1` не получается.

**Comment by PavelSyomin** [comment]
В чём проблема, понял. По поводу решения — в принципе могу поправить стили компонента, но мне кажется, что раз вы тоже умеете работать с CSS, то можете попробовать для полупрозрачности вместо `opacity` использовать такой код:
```
.proofreader_overlay {
    background-image: none;
    background-color: rgba(0, 0, 0, 0.5);
}
```

Разместите его в своей таблице стилей (главное — чтобы она загружалась позже той, которую использует компонент). Первое правило убирает фоновую картинку, второе — добавляет чёрный полупрозрачный фон. Последнее число в `rgba()` — это `opacity`.

**Comment by 1inkin** [comment]
Да, такой вариант работает, не знал о таком способе. Спасибо
