### ISSUE TITLE
Стилизация

### ISSUE THREAD

**Issue by 1inkin** [PavelSyomin/proofreader#4]
`h2` заголовка окна не имеет своего класса. конечно, к нему можно обратиться через родительские элементы, но все равно было бы удобнее с отдельным. 
`div proofreader_messages_container` открывается и сразу закрывается, хотя по идее должен включать в себя все элементы окна, кроме заголовка, что было бы удобно при стилизации и не пришлось бы обращаться к каждому элементу по отдельности.

**Comment by PavelSyomin** [comment]
Добавил класс к заголовку, поместил все остальные элементы формы в `div` со своим классом. По поводу `div.proofreader_messages_container` — честно говоря, не особо понимаю, зачем он вообще нужен. Может быть, какое-то легаси, которое осталось от старых версий и сейчас не используется. Оставил этот блок как есть, потому что на полный рефакторинг времени нет.

Все изменения вошли в версию 2.1.4 — тоже можете обновиться.

**Comment by 1inkin** [comment]
Это всё не принципиально, я с текущей разметкой сделал, как мне было нужно, просто написал, что заметил. Спасибо Вам за помощь и что доделали компонент под J4.
